### ISSUE TITLE
部署到 centos ，出现错误：【127.0.0.1:6379/0】The operation is not allowed on non-connected sockets

### ISSUE THREAD

**Issue by wanglixin** [2881099/im#42]
部署到 centos ，出现错误：【127.0.0.1:6379/0】The operation is not allowed on non-connected sockets

配置如下：
![image](https://user-images.githubusercontent.com/4438655/128157249-45d22788-ca8e-4a2e-8409-86dbbdaa2ec1.png)

**Comment by wanglixin** [comment]
Unhandled exception. System.Exception: 【127.0.0.1:6379/0】The operation is not allowed on non-connected sockets.
 ---> System.IO.IOException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.NetworkStream..ctor(Socket socket, FileAccess access, Boolean ownsSocket)
   at System.Net.Sockets.NetworkStream..ctor(Socket socket, Boolean ownsSocket)
   at FreeRedis.Internal.DefaultRedisSocket.Connect()
   at FreeRedis.Internal.DefaultRedisSocket.Write(CommandPacket cmd)
   at FreeRedis.RedisClient.SingleInsideAdapter.<>c__DisplayClass5_0`1.<AdapterCall>b__0()
   at FreeRedis.RedisClient.LogCall[T](CommandPacket cmd, Func`1 func)
   at FreeRedis.RedisClient.SingleInsideAdapter.AdapterCall[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Call[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Ping(String message)
   at FreeRedis.Internal.RedisClientPoolPolicy.PrevReheatConnectionPool(ObjectPool`1 pool, Int32 minPoolSize)
   --- End of inner exception stack trace ---
   at FreeRedis.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at FreeRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeRedis.RedisClient.PoolingAdapter.GetRedisSocket(CommandPacket cmd)
   at FreeRedis.RedisClient.PubSub.Subscribe(Boolean psub, String[] channels, Action`3 handler)
   at FreeRedis.RedisClient.Subscribe(String channel, Action`2 handler)
   at ImServer..ctor(ImServerOptions options) in D:\work\im\ImCore\ImServer.cs:line 61
   at ImServerExtenssions.<>c__DisplayClass1_0.<UseImServer>b__0(IApplicationBuilder appcur) in D:\work\im\ImCore\ImServer.cs:line 30
   at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Boolean preserveMatchedPathSegment, Action`1 configuration)
   at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
   at ImServerExtenssions.UseImServer(IApplicationBuilder app, ImServerOptions options) in D:\work\im\ImCore\ImServer.cs:line 28
   at imServer.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) in D:\work\im\imServer\Startup.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at imServer.Program.Main(String[] args) in D:\work\im\imServer\Program.cs:line 11
