### ISSUE TITLE
这个im支持发布在windows server 2016上吗？

### ISSUE THREAD

**Issue by zhaoguoping** [2881099/im#43]
这个im支持发布在windows server 2016上吗？

**Comment by zhaoguoping** [comment]
【127.0.0.1:6379/0】恢复检查时间：2021/8/28 18:25:54
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.Exception: 【127.0.0.1:6379/0】NOAUTH Authentication required.
 ---> FreeRedis.RedisServerException: NOAUTH Authentication required.
   at FreeRedis.RedisResult.ThrowOrValue[TValue](Func`2 value)
   at FreeRedis.RedisClient.<>c.<Ping>b__74_0(RedisResult rt)
   at FreeRedis.RedisClient.SingleInsideAdapter.<>c__DisplayClass5_0`1.<AdapterCall>b__0()
   at FreeRedis.RedisClient.LogCall[T](CommandPacket cmd, Func`1 func)
   at FreeRedis.RedisClient.SingleInsideAdapter.AdapterCall[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Call[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Ping(String message)
   at FreeRedis.Internal.RedisClientPoolPolicy.PrevReheatConnectionPool(ObjectPool`1 pool, Int32 minPoolSize)
   --- End of inner exception stack trace ---
   at FreeRedis.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at FreeRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeRedis.RedisClient.PoolingAdapter.GetRedisSocket(CommandPacket cmd)
   at FreeRedis.RedisClient.PubSub.Subscribe(Boolean psub, String[] channels, Action`3 handler)
   at FreeRedis.RedisClient.Subscribe(String channel, Action`2 handler)
   at ImServer..ctor(ImServerOptions options) in E:\New\YFSOFT.Net\YFSOFT.ImCore\ImServer.cs:line 62
   at ImServerExtenssions.<>c__DisplayClass1_0.<UseImServer>b__0(IApplicationBuilder appcur) in E:\New\YFSOFT.Net\YFSOFT.ImCore\ImServer.cs:line 30
   at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
   at ImServerExtenssions.UseImServer(IApplicationBuilder app, ImServerOptions options) in E:\New\YFSOFT.Net\YFSOFT.ImCore\ImServer.cs:line 39
   at imServer.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) in E:\New\YFSOFT.Net\YFSOFT.ImServer\Startup.cs:line 41
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Unhandled exception. System.Exception: 【127.0.0.1:6379/0】NOAUTH Authentication required.
 ---> FreeRedis.RedisServerException: NOAUTH Authentication required.
   at FreeRedis.RedisResult.ThrowOrValue[TValue](Func`2 value)
   at FreeRedis.RedisClient.<>c.<Ping>b__74_0(RedisResult rt)
   at FreeRedis.RedisClient.SingleInsideAdapter.<>c__DisplayClass5_0`1.<AdapterCall>b__0()
   at FreeRedis.RedisClient.LogCall[T](CommandPacket cmd, Func`1 func)
   at FreeRedis.RedisClient.SingleInsideAdapter.AdapterCall[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Call[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Ping(String message)
   at FreeRedis.Internal.RedisClientPoolPolicy.PrevReheatConnectionPool(ObjectPool`1 pool, Int32 minPoolSize)
   --- End of inner exception stack trace ---
   at FreeRedis.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at FreeRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeRedis.RedisClient.PoolingAdapter.GetRedisSocket(CommandPacket cmd)
   at FreeRedis.RedisClient.PubSub.Subscribe(Boolean psub, String[] channels, Action`3 handler)
   at FreeRedis.RedisClient.Subscribe(String channel, Action`2 handler)
   at ImServer..ctor(ImServerOptions options) in E:\New\YFSOFT.Net\YFSOFT.ImCore\ImServer.cs:line 62
   at ImServerExtenssions.<>c__DisplayClass1_0.<UseImServer>b__0(IApplicationBuilder appcur) in E:\New\YFSOFT.Net\YFSOFT.ImCore\ImServer.cs:line 30
   at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
   at ImServerExtenssions.UseImServer(IApplicationBuilder app, ImServerOptions options) in E:\New\YFSOFT.Net\YFSOFT.ImCore\ImServer.cs:line 39
   at imServer.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) in E:\New\YFSOFT.Net\YFSOFT.ImServer\Startup.cs:line 41
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at imServer.Program.Main(String[] args) in E:\New\YFSOFT.Net\YFSOFT.ImServer\Program.cs:line 12

**Comment by zhaoguoping** [comment]
在本地windows10 下，调试成功，当发布到windows server 2016上时，报了以上错误。。 这个支持最新版本的.net5.0和最新版本的.net core 3.1吗？

**Comment by zhaoguoping** [comment]
.NET SDK (反映任何 global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by 2881099** [comment]
NOAUTH Authentication required.

你 redis-server 没有密码
