### ISSUE TITLE
压测时候出现大量超时错误

### ISSUE THREAD

**Issue by a14907** [2881099/im#8]
日志是这样的：
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.TimeoutException: SafeObjectPool.Get 获取超时（10秒）。
   at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.HKeys(String key)
   at ImClient.GetChanListByClientId(Guid clientId) in D:\code\TT\001_src\im\ImCore\ImClient.cs:line 256
   at ImServer.Acceptor(HttpContext context, Func`1 next) in D:\code\TT\001_src\im\ImCore\ImServer.cs:line 116
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

是什么问题？

**Comment by 2881099** [comment]
poolsize设置的多少，csredis的配置，加大一些

**Comment by a14907** [comment]
> poolsize设置的多少，csredis的配置，加大一些

设置了100

**Comment by 2881099** [comment]
那就是处理不过来，把redis当本地试试，再不行就上redis集群
